//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactPerson
    {
        public int companyCode { get; set; }
        public int contacnPersonID { get; set; }
        public string department { get; set; }
        public string gender { get; set; }
        public string name { get; set; }
    
        public virtual customers customers { get; set; }
    }
}
