//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public customers()
        {
            this.contactPerson = new HashSet<contactPerson>();
            this.deliveryOrder = new HashSet<deliveryOrder>();
            this.inquiry = new HashSet<inquiry>();
            this.inquriy_ma = new HashSet<inquriy_ma>();
            this.invo_ma = new HashSet<invo_ma>();
            this.invoice = new HashSet<invoice>();
            this.out_ma = new HashSet<out_ma>();
            this.quo_ma = new HashSet<quo_ma>();
            this.quotation = new HashSet<quotation>();
            this.sales_ma = new HashSet<sales_ma>();
            this.salesOrder = new HashSet<salesOrder>();
        }
    
        public int companyCode { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public decimal texRate { get; set; }
    
        public virtual ICollection<contactPerson> contactPerson { get; set; }
        public virtual ICollection<deliveryOrder> deliveryOrder { get; set; }
        public virtual ICollection<inquiry> inquiry { get; set; }
        public virtual ICollection<inquriy_ma> inquriy_ma { get; set; }
        public virtual ICollection<invo_ma> invo_ma { get; set; }
        public virtual ICollection<invoice> invoice { get; set; }
        public virtual ICollection<out_ma> out_ma { get; set; }
        public virtual ICollection<quo_ma> quo_ma { get; set; }
        public virtual ICollection<quotation> quotation { get; set; }
        public virtual ICollection<sales_ma> sales_ma { get; set; }
        public virtual ICollection<salesOrder> salesOrder { get; set; }
    }
}
