//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_DBEntities : DbContext
    {
        public ERP_DBEntities()
            : base("name=ERP_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<contactPerson> contactPerson { get; set; }
        public DbSet<customers> customers { get; set; }
        public DbSet<deliveryOrder> deliveryOrder { get; set; }
        public DbSet<inquiry> inquiry { get; set; }
        public DbSet<inquriy_ma> inquriy_ma { get; set; }
        public DbSet<invo_ma> invo_ma { get; set; }
        public DbSet<invoice> invoice { get; set; }
        public DbSet<materials> materials { get; set; }
        public DbSet<orderForm> orderForm { get; set; }
        public DbSet<orderForm_ma> orderForm_ma { get; set; }
        public DbSet<out_ma> out_ma { get; set; }
        public DbSet<quo_ma> quo_ma { get; set; }
        public DbSet<quotation> quotation { get; set; }
        public DbSet<re_ven_ma> re_ven_ma { get; set; }
        public DbSet<receipt> receipt { get; set; }
        public DbSet<requisition> requisition { get; set; }
        public DbSet<rfq> rfq { get; set; }
        public DbSet<rfq_ven_ma> rfq_ven_ma { get; set; }
        public DbSet<sales_ma> sales_ma { get; set; }
        public DbSet<salesOrder> salesOrder { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<vendor> vendor { get; set; }
    }
}
