//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.invo_ma = new HashSet<invo_ma>();
        }
    
        public int companyCode { get; set; }
        public int invoiceID { get; set; }
        public Nullable<int> fiscalYear { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual ICollection<invo_ma> invo_ma { get; set; }
    }
}
