//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderForm
    {
        public orderForm()
        {
            this.orderForm_ma = new HashSet<orderForm_ma>();
        }
    
        public int vendorCode { get; set; }
        public int orderFormID { get; set; }
        public int rfqID { get; set; }
    
        public virtual ICollection<orderForm_ma> orderForm_ma { get; set; }
        public virtual rfq rfq { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
