//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class re_ven_ma
    {
        public int requisitionID { get; set; }
        public int materialID { get; set; }
        public int vendorCode { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual requisition requisition { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
