//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfq
    {
        public rfq()
        {
            this.orderForm = new HashSet<orderForm>();
            this.orderForm_ma = new HashSet<orderForm_ma>();
            this.rfq_ven_ma = new HashSet<rfq_ven_ma>();
        }
    
        public int rfqID { get; set; }
        public Nullable<System.DateTime> quotationDate { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        public virtual ICollection<orderForm> orderForm { get; set; }
        public virtual ICollection<orderForm_ma> orderForm_ma { get; set; }
        public virtual ICollection<rfq_ven_ma> rfq_ven_ma { get; set; }
    }
}
