//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesOrder
    {
        public salesOrder()
        {
            this.deliveryOrder = new HashSet<deliveryOrder>();
            this.out_ma = new HashSet<out_ma>();
            this.sales_ma = new HashSet<sales_ma>();
        }
    
        public int companyCode { get; set; }
        public int quotationID { get; set; }
        public int salesOrderID { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual ICollection<deliveryOrder> deliveryOrder { get; set; }
        public virtual ICollection<out_ma> out_ma { get; set; }
        public virtual quotation quotation { get; set; }
        public virtual ICollection<sales_ma> sales_ma { get; set; }
    }
}
