//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public vendor()
        {
            this.materials = new HashSet<materials>();
            this.orderForm = new HashSet<orderForm>();
            this.re_ven_ma = new HashSet<re_ven_ma>();
            this.receipt = new HashSet<receipt>();
            this.rfq_ven_ma = new HashSet<rfq_ven_ma>();
        }
    
        public int vendorCode { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> taxRate { get; set; }
    
        public virtual ICollection<materials> materials { get; set; }
        public virtual ICollection<orderForm> orderForm { get; set; }
        public virtual ICollection<re_ven_ma> re_ven_ma { get; set; }
        public virtual ICollection<receipt> receipt { get; set; }
        public virtual ICollection<rfq_ven_ma> rfq_ven_ma { get; set; }
    }
}
